<?php

?>
<div class="page-title">
    <h3><?php echo $this->__('Edit Account Information') ?></h3>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<form action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate">
<fieldset class="group-select">
    <?php echo $this->getBlockHtml('formkey')?>
    <h4 class="legend"><?php echo $this->__('Account Information') ?></h4>
    <ul>
        <li>
            <?php echo $this->getLayout()->createBlock('customer/widget_name')->setObject($this->getCustomer())->toHtml() ?></li>
        <li>
            <div class="input-box">
            <label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
            <input type="text" name="email" id="email" value="<?php echo $this->htmlEscape($this->getCustomer()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="required-entry validate-email input-text" />
            </div>
        </li>

<?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
<?php if ($_dob->isEnabled()): ?>
        <li><?php echo $_dob->setDate($this->getCustomer()->getDob())->toHtml() ?></li>
<?php endif ?>
<?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
<?php if ($_taxvat->isEnabled()): ?>
        <li><?php echo $_taxvat->setTaxvat($this->getCustomer()->getTaxvat())->toHtml() ?></li>
<?php endif ?>
    </ul>
	<br/>
	<p><input type="checkbox" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>"<?php if($this->getCustomer()->getChangePassword()==1): ?> checked="checked"<?php endif; ?> /> <label for="change_password"><?php echo $this->__('Change Password') ?></label>
	</p>
	<fieldset class="group-select" style="display:none">
	    <h4 class="legend"><?php echo $this->__('Change Password') ?></h4>
	    <ul>
	        <li>
	            <div class="input-box">
	                <label for="current_password"><?php echo $this->__('Current Password') ?></label><br/>
	                <input type="password" class="input-text" name="current_password" id="current_password" />
	            </div>
	        </li>
	        <li>
	            <div class="input-box">
	                <label for="password"><?php echo $this->__('New Password') ?></label><br/>
	                <input type="password" class="validate-password input-text" name="password" id="password" />
	            </div>
	            <div class="input-box">
	                <label for="confirmation"><?php echo $this->__('Confirm New Password') ?></label><br/>
	                <input type="password" class="validate-cpassword input-text" name="confirmation" id="confirmation" />
	            </div>
	        </li>
	    </ul>
	</fieldset>
	<div class="button-set" style="margin:0">
		<p class="required"><?php echo $this->__('* Required Fields') ?></p>
	    <button type="submit" class="form-button"><span><?php echo $this->__('Save Account Information') ?></span></button>
	</div>
</fieldset>
</form>

<form action="<?php echo $this->getUrl('customer/account/editProfile') ?>" enctype="multipart/form-data" method="post" id="form-validate">
<fieldset class="group-select">
    <?php echo $this->getBlockHtml('formkey')?>
    <h4 class="legend"><?php echo $this->__('Profile') ?></h4>
    <table width="100%">
    	<tr>
    		<td>
				<ul>
			        <li>
			            <div class="input-box">
			            <label for="nickname"><?php echo $this->__('Screen name') ?></label><br />
			            <input type="text" name="nickname" id="nickname" value="<?php echo $this->htmlEscape($this->getCustomer()->getNickname()) ?>" title="<?php echo $this->__('Screen name') ?>" class="input-text" />
			            </div>
			        </li>
			        <li>
			            <div class="input-box">
			            <label for="gender"><?php echo $this->__('Gender') ?></label><br />
			            <?php echo $this->getGenderHtmlSelect('male', 'gender', 'gender', 'Gender') ?>
			            </div>
			        </li>
			        <li>
			            <div class="input-box">
			            <label for="shortprofile"><?php echo $this->__('Short profile') ?></label><br />
						<textarea name="shortprofile" id="shortprofile" style="width:375px; overflow: auto;" cols="1" rows="3"  ><?php echo $this->htmlEscape($this->getCustomer()->getShortprofile()) ?></textarea>
			            </div>
			        </li>
			        <li>
			            <div class="input-box">
			            <!-- <h4>File Upload</h4> -->
			            <label for="file"><?php echo $this->__('Avatar') ?></label><br />
			            <input type="file" name="avatar" size="33"><br clear="all"/>
			            </div>
			        </li>
			    </ul>
    		</td>
    		<td width="40%" align="center">
    			<?php echo $this->getAvatar($this->getCustomer()->getId()); ?>
    		</td>
    	<tr>
    </table>


	<div class="button-set" style="margin:0">
	    <button type="submit" class="form-button"><span><?php echo $this->__('Save Profile') ?></span></button>
	</div>
</fieldset>
</form>
<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>

<script type="text/javascript">
//<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }
    <?php if($this->getCustomer()->getChangePassword()): ?>
        setPasswordForm(true);
    <?php endif; ?>
//]]>
</script>
