<?php $limit = 0; foreach ($this->getStoreCategories() as $_category): ?>
<?php $open = $this->isCategoryActive($_category); ?>
<?php

    $cur_category=Mage::getModel('catalog/category')->load($_category->getId());
    $layer = Mage::getSingleton('catalog/layer');
    $layer->setCurrentCategory($cur_category);
    if ($immagine = $this->getCurrentCategory()->getImageUrl()):
        ?>
    <li class="mosaic-block bar">

        <a href="<?php echo $this->getCategoryUrl($_category)?>" class="mosaic-overlay"><div class="details"><h5><?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?></h5></div></a>
        <!--	<a href="sell-your-item.html"><h5 class="">Sell</h5></a>



                    <div class="mosaic-backdrop"><img src="<?php echo $immagine ?>" alt="<?php echo $this->htmlEscape($this->getCurrentCategory()->getName()) ?>" width="214" height="192" />  </div>    -->
        <a href="<?php echo $this->getCategoryUrl($_category)?>" class="mosaic-backdrop"><img src="<?php echo $immagine ?>"  width="214" height="192" /></a>

    </li>
    </a>



    <?php

        endif;
        $limit+=1;
        if ($limit==8):
            break;
        endif;
endforeach; ?>