<?php 
/**
 * All For Coding
 *
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 All For Coding. (http://www.all4coding.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */

/* @var $this Mage_Core_Block_Template */

?>
<?php if (Mage::getStoreConfig('a4c_facebook/general/enabled')) : ?>   
<fb:facepile 
href="<?php echo (Mage::getStoreConfig('a4c_facebook/facepile/url') == 'currentpage') ? $this->helper('core/url')->getCurrentUrl() : Mage::getStoreConfig('a4c_facebook/general/fb_page_url'); ?>" 
size="<?php echo Mage::getStoreConfig('a4c_facebook/facepile/size'); ?>" 
max_rows="<?php echo Mage::getStoreConfig('a4c_facebook/facepile/max_rows'); ?>"
width="<?php echo Mage::getStoreConfig('a4c_facebook/facepile/width'); ?>"
colorscheme="<?php echo Mage::getStoreConfig('a4c_facebook/facepile/colorscheme'); ?>"></fb:facepile>
<?php endif; ?>