<div class="page-title">
    <h1><?php echo $this->__('Edit Advertisement') ?></h1>
</div>
<?php
if (isset($_GET['id'])) {
    $id = $_GET['id'];
}

$product = Mage::getModel('catalog/product')->load($id);
$cateid = $product->getCategoryIds();
$cateid = $cateid[0];


if (isset($_POST) && !empty($_POST['request_flag'])):
    $params = $this->getRequest()->getParams();
    // print_r($params);
    // exit();
    $customer = Mage::getSingleton('customer/session')->getCustomer();
    $sellerId = $customer->getentity_id();

    if (isset($_POST['phone_check'])) {
        $customerAddressId = $customer->getDefaultBilling();
        if ($customerAddressId) {
            $customAddress = Mage::getModel('customer/address')->load($customerAddressId);
            $customAddress->setTelephone($params['phone']);
        }
        try {
            $customAddress->save();
        } catch (Exception $ex) {
            Zend_Debug::dump($ex->getMessage());
        }
    }
    if (isset($_POST['negotiable'])) {
        $newProduct->setNegotiable('1');
    }

    $product->setAttributeSetId(4);
    $product->setName($params['title']);
    $product->setCategoryIds(array($params['ad-category']));
    $product->setShortDescription($params['product_description']);
    $product->setPrice($params['price']);
    //$product->setSeller($params['name']);
    $product->setPhone($params['phone']);
    //$product->setLocation($params['location']);
    //$product->setEmail($params['email']);
    $product->setStoreID(0);
    $product->setStatus('3');
    $product->setLiveSent('0');
    //$tagName = $params['tags'];

    if ($product->save()) {
        $advertiser_email = $product->getEmail();
         $ad_id = $product->getentity_id();
        $proName = $product->getName();
        $proComment = $product->getComment();
        $advertiser = $product->getSeller();
        $AdUrl = Mage::getModel('catalog/product')->load($ad_id)->getProductUrl();
                          $templateId = 6;

        // Define the sender, here we query Magento default email (in the configuration)
        // For customer support email, use : 'trans_email/ident_support/...'
         $sender =  Array('name' => 'NotunBazar', 'email' => 'contact@notunbazar.com');
        // Set you store
        // This information may be taken from the current logged in user
           $store = Mage::app()->getStore();
        // In this array, you set the variables you use in your template
           $vars = Array(
               'proName' => $proName,
               'proComment' => $proComment,
               'advertiser' => $advertiser,
               'proUrl' => $AdUrl,
               'logo_path' => 'http://notunbazar.com/skin/frontend/default/abac/images/logo.png'
           );

        // Send your email
        $translate  = Mage::getSingleton('core/translate');

        Mage::getModel('core/email_template')->sendTransactional($templateId,
               $sender,
               $advertiser_email,
               $advertiser,
              $vars,
               $store->getId());
               
                      Mage::getModel('core/email_template')->sendTransactional($templateId,
               $sender,
               'contact@notunbazar.com',
               'Notunbazar Admin',
              $vars,
               $store->getId());

           $translate->setTranslateInline(true);
        /*         * ****Save keywords*************** */
        if ($tagName != "") {
            $tagName = $params['tags'];
            $customerID = NULL;
            $storeId = Mage::app()->getStore()->getId();
            $productID = $product->getId();

            $tagModel = Mage::getModel('tag/tag');

            function _extractTags($tagName) {
                return explode("\n", preg_replace("/(\'(.*?)\')|(\s+)/i", "$1\n", $tagName));
            }

            function _cleanTags(array $tagNamesArr) {
                foreach ($tagNamesArr as $key => $tagName) {
                    $tagNamesArr[$key] = trim($tagNamesArr[$key], '\'');
                    $tagNamesArr[$key] = trim($tagNamesArr[$key]);
                    if ($tagNamesArr[$key] == '') {
                        unset($tagNamesArr[$key]);
                    }
                }
                return $tagNamesArr;
            }

            $tagNamesArr = _cleanTags(_extractTags($tagName));
            foreach ($tagNamesArr as $tagName) {
                $tagModel->loadByName($tagName);
                //$tagModel->unsetData()->loadByName($tagName);  //if using a loop

                if (!$tagModel->getId()) {
                    $tagModel->setName($tagName)
                            ->setFirstCustomerId($customerId)
                            ->setFirstStoreId($storeId)
                            ->setStatus($tagModel->getPendingStatus())
                            ->save();
                }

                $relationStatus = $tagModel->saveRelation($productID, $customerId, $storeId);
            }
        }
        /*         * ************End************** */
        Mage::getSingleton('core/session')->addSuccess($this->__('Advertisement has been successfully updated.'));
        Mage::app()->getResponse()->setRedirect(Mage::getBaseUrl() . 'classified/myad');
    }

endif;
?>

<form method="post" name="sale_form" action="" class="sale_form" id="sale_form" enctype="multipart/form-data">
    <div style="width: 630px; float: left;">
        <div style="margin-left: 20px;">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Ad Information') ?></h2>
                <label for="ad-category" class="label-text required"><?php echo $this->__('Select Category') ?> <span class="red">*</span></label>
                <?php
                $_helper = Mage::helper('catalog/category');
                $_categories = $_helper->getStoreCategories();
                if (count($_categories) > 0):
                    ?>
                    <select class="cate-se validate-select" id="cate-top" name="ad-category">
                        <option style="color: #2F2F2F; font-weight: bold;" value=""><?php echo $this->__('Select one') ?></option>
                        <?php foreach ($_categories as $_category): ?>

                            <option style="color: #2F2F2F; font-weight: bold;" value="<?php echo $_category->getId() ?>" <?php if ($cateid == $_category->getId()): ?>selected="selected"<?php endif; ?>>
                                <?php echo $_category->getName() ?>
                            </option>
                            <?php $_category = Mage::getModel('catalog/category')->load($_category->getId()) ?><?php $_subcategories = $_category->getChildrenCategories() ?>
                            <?php if (count($_subcategories) > 0): ?>
                                <?php foreach ($_subcategories as $_subcategory): ?>
                                    <option style="color: #2F2F2F ;font-size: 12px;" value="<?php echo $_subcategory->getId() ?>"  <?php if ($cateid == $_subcategory->getId()): ?>selected="selected"<?php endif; ?>>  <?php echo '&nbsp' . '&nbsp' . '|-- ' . $_subcategory->getName() ?>
                                    </option>
                                <?php endforeach; ?>
                            <?php endif; ?>
                        <?php endforeach; ?><?php endif; ?>
                </select>
                <p class="clr">&nbsp;</p>
                <label for="title" class="label-text required"><?php echo $this->__('Ad Title') ?><span class="red">*</span></label>
                <input id="" type="text" class="input-field required-entry" name="title" value="<?php echo $product->getName(); ?>" />
                <p class="clr">&nbsp;</p>

                <p class="label-text"><?php echo $this->__('Ad Description') ?></p>
                <textarea id="textarea"  name="product_description" style="height: 115px;" class="con-textarea input-field"><?php echo $product->getShortDescription(); ?></textarea>
                <ul class="note"><li><?php echo $this->__('Including more details will help you getting better responses') ?></li></ul>
                <p class="clr">&nbsp;</p>

                <label for="price" class="label-text required"><?php echo $this->__('Desired Price (Tk.)') ?> <span class="red">*</span></label>
                <input id=""  type="text" name="price" value="<?php echo $product->getPrice(); ?>"  class="input-field required-entry validate-number" /><br>
                <div class="check"><input type="checkbox" name="negotiable" value="Yes" /><?php echo $this->__('Private (Select, if you don\'t want to publish the price)') ?></div>
                <p class="clr">&nbsp;</p>

                <label for="tags" class="label-text"><?php echo $this->__('Keywords') ?></label>
                <input id="tags"  type="text" class="input-field" name="tags" value="" /> <br>
                <ul class="note">
                    <li>
                        <?php echo $this->__('Use spaces to separate tags. Use single quotes (\') for phrases') ?>
                    </li>
                    <li>
                        <?php echo $this->__('Including relevant keywords will make your ad more discoverable') ?>
                    </li>
                </ul>
                <p class="clr">&nbsp;</p>

                <?php
                $read = Mage::getSingleton('core/resource')->getConnection('core_read');
                $country = $product->getCountry();
                $state = $product->getStateDistrict();
                $city = $product->getRegionCity();
                $table_country_region = Mage::getSingleton('core/resource')->getTableName('country_region');
                $table_eav_attribute_option = Mage::getSingleton('core/resource')->getTableName('eav_attribute_option');
                $table_eav_attribute_option_value = Mage::getSingleton('core/resource')->getTableName('eav_attribute_option_value');
                $resultCountry = $read->query("SELECT DISTINCT t1.option_id as id, t2.value as country FROM " . $table_eav_attribute_option . " as t1 INNER JOIN " . $table_eav_attribute_option_value . " as t2 where t1.attribute_id = 147 and t1.option_id = t2.option_id ORDER BY country ASC");
                ?>
                <label for="country" class="label-text"><?php echo $this->__('Country') ?></label>                            
                <select name="country" id="country" onChange="getState(this.value)" class="cate-se validate-select">
                    <option value>Country</option>
                    <?php while ($rowCountry = $resultCountry->fetch(PDO::FETCH_ASSOC)) { ?>
                        <option value="<?php echo $rowCountry['id'] ?>" <?php if ($rowCountry['id'] == $country): ?>selected="selected"<?php endif; ?>><?php echo $rowCountry['country'] ?></option>

                    <?php } ?>
                </select>
                <p class="clr">&nbsp;</p>
                
                <div id="state_city" style="display:none">
                    <?php $resultState = $read->query("SELECT t1.state_id as id, t2.value as statename FROM " . $table_country_region . " as t1 INNER JOIN  " . $table_eav_attribute_option_value . "  as t2 where t1.country_id = " . $country . " and t2.store_id = 0 and t1.state_id = t2.option_id ORDER BY statename ASC"); ?>
                    <label for="state_district" class="label-text"><?php echo $this->__('State/District') ?>
                        <span class="red">*</span>
                    </label>
                    <div id="statediv">
                        <select name="state_district" id="state_district" onchange="getCity(<?php echo $product->getCountry(); ?>, this.value)" class="cate-se validate-select">
                            <option>Select State</option>
                            <?php while ($rowState = $resultState->fetch(PDO::FETCH_ASSOC)) { ?>
                                <option value=<?php echo $rowState['id'] ?> <?php if ($rowState['id'] == $product->getStateDistrict()): ?>selected="selected"<?php endif; ?>><?php echo $rowState['statename'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <p class="clr">&nbsp;</p>
                    <?php
                    $resultCity = $read->query("SELECT t1.region_id as id, t2.value as regionname FROM " . $table_country_region . " as t1 INNER JOIN " . $table_eav_attribute_option_value . " as t2 where t1.country_id = " . $country . " and  t1.state_id = " . $state . " and t2.store_id = 0 and t1.region_id = t2.option_id ORDER BY regionname ASC");
                    ?>
                    <label for="region_city" class="label-text"><?php echo $this->__('Region/City') ?></label>
                    <div id="citydiv">
                        <select name="region_city" id="region_city" class="cate-se validate-select">
                            <option>Select City</option>
                            <?php while ($rowCity = $resultCity->fetch(PDO::FETCH_ASSOC)) { ?>
                                <option value=<?php echo $rowCity['id'] ?> <?php if ($rowCity['id'] == $city): ?>selected="selected"<?php endif; ?>><?php echo $rowCity['regionname'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                    <p class="clr">&nbsp;</p>
                </div>
            </div>


            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Advertiser Information') ?></h2>
                <label for="phone" class="label-text required"><?php echo $this->__('Phone Number') ?> <span class="red">*</span></label>
                <input id="phone" type="text" class="input-field required-entry" name="phone"  onclick="check_phone();" value="<?php echo $product->getPhone(); ?>" />
                <input id="email" type="hidden" class="input-field" name="email" value="<?php echo $product->getEmail(); ?>"/>
                <div id="check-phone" class="check" style="display: none"><input type="checkbox" name="phone_check" value="Yes"/> <?php echo $this->__('Check to update with your account Phone Number') ?></div>

                <p class="clr">&nbsp;</p>
            </div>
            <div class="buttons-set">
                <p class="back-link"><a href="#" onclick="history.back();
                        return false;"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
                <button type="submit" title="Submit" class="button validation-passed"><span><span><?php echo $this->__('Update') ?></span></span></button>
            </div>
        </div>
    </div>
    <input type="hidden" name="request_flag" value="1"/>
</form>
<script type="text/javascript">
    jQuery(document).ready(function () {
        if (jQuery("#country option:selected").text() == "Bangladesh") {
                jQuery("#state_city").show(500);
            }
            else
            {
                jQuery("#state_city").hide(500);
            }
        jQuery("#country").change(function () {
            if (jQuery("#country option:selected").text() == "Bangladesh") {
                jQuery("#state_city").show(500);
            }
            else
            {
                jQuery("#state_city").hide(500);
            }
        });
    });
</script>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('sale_form', true);
    //]]>
</script>
<script type="text/javascript">
    function check_phone() {
        var elem = document.getElementById("check-phone");
        elem.style.display = "block";
    }
//    function check_location(){
//        var elem = document.getElementById("check-loc");
//        elem.style.display = "block";
//    }
</script>
<script language="javascript" type="text/javascript">
    function getXMLHTTP() { //fuction to return the xml http object
        var xmlhttp = false;
        try {
            xmlhttp = new XMLHttpRequest();
        }
        catch (e) {
            try {
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            catch (e) {
                try {
                    xmlhttp = new ActiveXObject("Msxml2.XMLHTTP");
                }
                catch (e1) {
                    xmlhttp = false;
                }
            }
        }

        return xmlhttp;
    }

    function getState(countryId) {

        var strURL = "/findState.php?country=" + countryId;
        //Mage::getModuleDir('Helper', 'Your_Extension');
        var req = getXMLHTTP();

        if (req) {

            req.onreadystatechange = function () {
                if (req.readyState == 4) {
                    // only if "OK"
                    if (req.status == 200) {
                        document.getElementById('statediv').innerHTML = req.responseText;
                        document.getElementById('citydiv').innerHTML = '<select name="city" class="cate-se validate-select">' +
                                '<option>Select City</option>' +
                                '</select>';
                    } else {
                        alert("Problem while using XMLHTTP:\n" + req.statusText);
                    }
                }
            }
            req.open("GET", strURL, true);
            req.send(null);
        }
    }
    function getCity(countryId, stateId) {
        var strURL = "/findCity.php?country=" + countryId + "&state=" + stateId;
        var req = getXMLHTTP();

        if (req) {

            req.onreadystatechange = function () {
                if (req.readyState == 4) {
                    // only if "OK"
                    if (req.status == 200) {
                        document.getElementById('citydiv').innerHTML = req.responseText;
                    } else {
                        alert("Problem while using XMLHTTP:\n" + req.statusText);
                    }
                }
            }
            req.open("GET", strURL, true);
            req.send(null);
        }

    }
</script>