<style type="text/css">

    #messagebox{
        height: 300px;
        width: 544px;
        overflow-y: scroll;
    }
    #body{
        width: 544px;
    }
    .toggle{
        cursor: pointer;
    }

</style>

<script type="text/javascript">
    function toggleMe(a){
        var e=document.getElementById(a);
        if(!e)return true;
        if(e.style.display=="none"){
            e.style.display="block"
        }
        else{
            e.style.display="none"
        }
        return true;
    }
    function confirm_delete(cId) {
        var answer = confirm("Are you sure want to delete this conversation?")
        if (answer){
            //alert("Entry Deleted");
            window.location = "?id="+cId+"&cid="+cId;
        }
        else{
            exit();
        }
    }

    function confirm_delete_message (mId, id) {
        var answer = confirm("Are you sure want to delete this message?")
        if (answer){
            //alert("Entry Deleted");
            window.location = "?id="+id+"&mid="+mId;
        }
        else{
            exit();
        }
    }
</script>
<?php
$customer = Mage::getSingleton('customer/session')->getCustomer();
$sellerId = $customer->getentity_id();

$table_messages_body = Mage::getSingleton('core/resource')->getTableName('messages_body'); //table name
$table_messages = Mage::getSingleton('core/resource')->getTableName('messages'); //table name

if(isset($_GET['id']))
{
    $id = $_GET['id'];
    
    $sql = "SELECT * FROM $table_messages WHERE mssg_id='$id'";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
    foreach ($connection->fetchAll($sql) as $arr_row):
        $ad_id = $arr_row['ad_id'];
        $mssg_title = $arr_row['mssg_title'];
        $auth_a_conv = $arr_row['auth_a'];
        $auth_b_conv = $arr_row['auth_b'];
    endforeach;

    if($sellerId==$auth_a_conv)
    {        
        $sql = "update $table_messages set not_read_by_a='' where mssg_id='$id'";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
        $connection->query($sql);
    }
    if($sellerId==$auth_b_conv)
    {        
        $sql = "update $table_messages set not_read_by_b='' where mssg_id='$id'";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
        $connection->query($sql);
    }
}

if(isset($_GET['cid']))
{
    $cid = $_GET['cid'];
    
    $sql = "update $table_messages set auth_b=NULL where mssg_id='$cid' and auth_b='$sellerId'";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
    $connection->query($sql);
    
    $sql = "update $table_messages set auth_a=NULL where mssg_id='$cid' and auth_a='$sellerId'";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
    $connection->query($sql);

    header( 'Location: '. $this->getUrl('classified/message/')) ;
    exit;

}

if(isset($_GET['mid']))
{
    $mid = $_GET['mid'];
    
    $sql = "update $table_messages_body set auth_b=NULL where id='$mid' and auth_b='$sellerId'";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
    $connection->query($sql);
    
    $sql = "update $table_messages_body set auth_a=NULL where id='$mid' and auth_a='$sellerId'";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
    $connection->query($sql);

}

$sql = "SELECT * FROM $table_messages WHERE mssg_id='$id'";
$connection = Mage::getSingleton('core/resource')->getConnection('core_read');
foreach ($connection->fetchAll($sql) as $arr_row):
    $ad_id = $arr_row['ad_id'];
    $mssg_title = $arr_row['mssg_title'];
    $auth_a_conv = $arr_row['auth_a'];
    $auth_b_conv = $arr_row['auth_b'];
endforeach;
$AdUrl = Mage::getModel('catalog/product')->load($ad_id)->getProductUrl();


if(isset($_POST) && !empty($_POST['request_flag'])):
    $params = $this->getRequest()->getParams();
    
    $sql = "SELECT * FROM $table_messages WHERE mssg_id='$id'";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
    foreach ($connection->fetchAll($sql) as $arr_row):
        $ad_id = $arr_row['ad_id'];
        $mssg_title = $arr_row['mssg_title'];
        $auth_a_conv = $arr_row['auth_a'];
        $auth_b_conv = $arr_row['auth_b'];
    endforeach;

    if($sellerId==$auth_a_conv)
    {
       $receiver_id = $auth_b_conv;
    }
    else
    {
        $receiver_id =  $auth_a_conv;
    }

// Define the sender, here we query Magento default email (in the configuration)
// For customer support email, use : 'trans_email/ident_support/...'
    $mssg_id = $params['mssg_id'];
    $sender_id = $sellerId;
    $sender_message = $params['message'];
    $created = date("Y-m-d H:i:s", time());

    $customer_data = Mage::getModel('customer/customer')->load($sender_id);
    $firstname = $customer_data->getFirstname();
    $lastname = $customer_data->getLastname();
    $sender_name = $firstname ." ". $lastname;
    $sender_email = $customer_data->getEmail();

    $customer_data = Mage::getModel('customer/customer')->load($receiver_id);
    $firstname_rcv = $customer_data->getFirstname();
    $lastname_rcv = $customer_data->getLastname();
    $rcv_name = $firstname_rcv ." ". $lastname_rcv;
    $rcv_email = $customer_data->getEmail();
    
    $sql = "INSERT INTO $table_messages_body (mssg_id, sender_name, sender_id, sender_email, receiver_id, mssg, created, auth_a, auth_b) VALUES ('$mssg_id', '$sender_name','$sender_id','$sender_email','$receiver_id','$sender_message','$created', '$sender_id', '$receiver_id')";
    $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
    $connection->query($sql);

    if($sender_id==$auth_a_conv)
    {        
        $sql = "update $table_messages set not_read_by_a='' where mssg_id='$mssg_id'";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
        $connection->query($sql);
    }
    
    else
    {        
        $sql = "update $table_messages set not_read_by_b='' where mssg_id='$mssg_id'";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
        $connection->query($sql);
    }
    if($receiver_id==$auth_a_conv)
    {
        $sql = "update $table_messages set not_read_by_a='$receiver_id' where mssg_id='$mssg_id'";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
        $connection->query($sql);
    }
    else
    {
        $sql = "update $table_messages set not_read_by_b='$receiver_id' where mssg_id='$mssg_id'";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_write');
        $connection->query($sql);
    }


    // Set you store
// This information may be taken from the current logged in user
    /*   $templateId = 3;

   // Define the sender, here we query Magento default email (in the configuration)
   // For customer support email, use : 'trans_email/ident_support/...'
       $sender =  Array('name' => $sender_name, 'email' => $sender_email);
   // Set you store
   // This information may be taken from the current logged in user
       $store = Mage::app()->getStore();
   // In this array, you set the variables you use in your template
       $vars = Array(
           'proName' => $mssg_title,
           'email_sender' => $sender_email,
           'senderName' => $sender_name,
           'seller' => $rcv_name,
           'proUrl' => $AdUrl
       );

   // Send your email
       $translate  = Mage::getSingleton('core/translate');
       Mage::getModel('core/email_template')->sendTransactional($templateId,
           $sender,
           $rcv_email,
           $rcv_name,
           $vars,
           $store->getId());

       $translate->setTranslateInline(true);
       Mage::getSingleton('catalog/session')->addSuccess($this->__('Your message has been sent.'));
       header( 'Location:'. $this->getUrl('classified/message/')  ) ;
       exit(); */
    //custom-end

endif;


if($auth_a_conv==$sellerId || $auth_b_conv==$sellerId):

    echo '<h1>'.$mssg_title.'</h1>';

    ?>


<div id="body">
    <p style="text-align: right"><a href="javascript:confirm_delete(<?php echo $id; ?>)">Delete this conversation</a></p>
    <div id="messagebox">

        <?php
        $sql = "SELECT * FROM $table_messages_body WHERE mssg_id='$id' and (auth_a='$sellerId' or auth_b='$sellerId')";
        $connection = Mage::getSingleton('core/resource')->getConnection('core_read');
        foreach ($connection->fetchAll($sql) as $arr_row):
            $msgid = $arr_row['id'];
            $sender_id = $arr_row['sender_id'];
            $sender_name = $arr_row['sender_name'];
            $sender_email = $arr_row['sender_email'];
            $message = $arr_row['mssg'];
            $receiver_id = $arr_row['receiver_id'];
            $created = strtotime($arr_row['created']);
            $fdate = Date("D, M j, Y, g:i a", $created);

            $customer_data = Mage::getModel('customer/customer')->load($receiver_id);
            $firstname = $customer_data->getFirstname();
            $lastname = $customer_data->getLastname();
            $fullname = $firstname ." ". $lastname;
            $receiver_email = $customer_data->getEmail();


            ?>

            <table class="data-table">
                <thead>
                <tr>
                    <th class="toggle" onclick="return toggleMe('<?php echo $msgid; ?>')"><?php echo $sender_name; ?></th>
                    <th class="toggle" onclick="return toggleMe('<?php echo $msgid; ?>')"></th>
                    <th class="toggle" style="text-align: right" onclick="return toggleMe('<?php echo $msgid; ?>')"><?php echo $fdate; ?></th>
                    <th style="text-align: right" ><a href="javascript:confirm_delete_message(<?php echo $msgid.','. $id; ?>)"><img src=<?php echo $this->getSkinUrl('images/delete.png') ?> alt="Delete"> </a></th>
                </tr>
                </thead>
                <tbody >
                <td colspan="4" id="<?php echo $msgid; ?>"></br><?php echo $message; ?></br>&nbsp</td>
                </tbody>
            </table>

            <?php endforeach; ?>

    </div>
    <form action="" method="post" name="product_sendtofriend_form" id="product_sendtofriend_form" enctype="multipart/form-data">
        <div class="fieldset">
            <ul class="form-list" id="sender_options">
                <li class="wide">
                    <label for="sender_message" class="required"><em>*</em><?php echo $this->__('Reply:') ?></label>
                    <div class="input-box">
                        <textarea name="message" class="input-text required-entry" id="sender_message" cols="3" rows="3"></textarea>
                    </div>
                </li>
            </ul>
        </div>
        <div class="buttons-set">
            <p class="back-link"><a href="<?php echo $this->getUrl('classified/message/') ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>
            <button type="submit" class="button disabled="disabled"><span><span><?php echo $this->__('Send') ?></span></span></button>
        </div>
        <input type="hidden" name="request_flag" value="1"/>
        <input type="hidden" name="mssg_id" value="<?php echo $id ?>"/>
    </form>

</div>

<?php else: ?>
<?php     header( 'Location: '. $this->getUrl('classified/message/')) ;
    exit;
    ?>
<?php endif; ?>

<script type="text/javascript">
    //<![CDATA[
    var productSendtofriendForm = new VarienForm('product_sendtofriend_form');
    productSendtofriendForm.submit = function() {
        if(this.validator.validate()) {
            this.form.submit();
        }
    }.bind(productSendtofriendForm);
    //]]>
</script>
