<?php if (Mage::getStoreConfig('facebook/general/enabled')) : ?>   
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/<?php echo (Mage::getStoreConfig('facebook/general/locale') == 'auto') ? Mage::app()->getLocale()->getDefaultLocale() : Mage::getStoreConfig('facebook/general/locale'); ?>/all.js#appId=<?php echo Mage::getStoreConfig('facebook/general/appid'); ?>&amp;xfbml=1"></script>
    <fb:facepile href="<?php echo (Mage::getStoreConfig('facebook/facepile/url') == 'currentpage') ? $this->helper('core/url')->getCurrentUrl() : Mage::getStoreConfig('facebook/general/fb_page_url'); ?>" size="<?php echo Mage::getStoreConfig('facebook/facepile/size'); ?>" width="<?php echo Mage::getStoreConfig('facebook/facepile/width'); ?>" max_rows="<?php echo Mage::getStoreConfig('facebook/facepile/max_rows'); ?>"></fb:facepile>
<?php endif; ?>
