<meta property="fb:app_id" content="<?php echo Mage::getStoreConfig('facebook/general/appid'); ?>"/>
<meta property="og:type" content="<?php echo Mage::getStoreConfig('facebook/likebutton/type'); ?>" />
<meta property="og:url" content="<?php echo $this->helper('core/url')->getCurrentUrl();?>" />
<meta property="og:site_name" content="<?php echo Mage::app()->getStore()->getName(); ?>" />
<?php if (Mage::registry('current_product')) : ?>
<meta property="og:image" content="<?php echo Mage::helper('catalog/image')->init(Mage::registry('current_product'), 'small_image')->resize(100,100);?>" />
<meta property="og:title" content="<?php echo Mage::registry('current_product')->getName(); ?>" /> 
<?php else : ?>
<meta property="og:image" content="<?php echo Mage::getSingleton('core/layout')->getBlock('head')->getFaviconFile(); ?>" />
<meta property="og:title" content="<?php echo $this->getLayout()->getBlock('head')->getTitle(); ?>" /> 
<?php endif; ?>
