<?php if (Mage::getStoreConfig('facebook/general/enabled')) : ?>   
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/<?php echo (Mage::getStoreConfig('facebook/general/locale') == 'auto') ? Mage::app()->getLocale()->getDefaultLocale() : Mage::getStoreConfig('facebook/general/locale'); ?>/all.js#xfbml=1"></script>
    <fb:recommendations site="<?php echo $this->helper('core/url')->getCurrentUrl(); ?>" width="<?php echo Mage::getStoreConfig('facebook/recommendations/width'); ?>" height="<?php echo Mage::getStoreConfig('facebook/recommendations/height'); ?>" header="<?php echo (Mage::getStoreConfig('facebook/recommendations/header')) ? 'true' : 'false'; ?>" font="<?php echo Mage::getStoreConfig('facebook/recommendations/font'); ?>" border_color="<?php echo Mage::getStoreConfig('facebook/recommendations/border_color'); ?>"></fb:recommendations>

<?php endif; ?>

