<?php if (Mage::getStoreConfig('facebook/general/enabled')) : ?>   
    <div id="fb-root"></div>
    <script src="http://connect.facebook.net/<?php echo (Mage::getStoreConfig('facebook/general/locale') == 'auto') ? Mage::app()->getLocale()->getDefaultLocale() : Mage::getStoreConfig('facebook/general/locale'); ?>/all.js#xfbml=1"></script>
    <fb:send href="<?php echo $this->helper('core/url')->getCurrentUrl();?>" font="<?php echo Mage::getStoreConfig('facebook/likebutton/font'); ?>"></fb:send>
<?php endif; ?>